### ISSUE TITLE
Looks very interesting!!

### ISSUE THREAD

**Issue by kieranjol** [kfrn/smpte-colourbars#1]
Hi, is the goal of this to make colour bars via code? I don't know much about SVG.

**Comment by kfrn** [comment]
Hey @kieranjol! Yes that's the idea, though as yet they are just blue oblongs. I'm trying to learn more about SVG and [D3](https://d3js.org/), which is a super cool JavaScript library for data visualisation.  
Watch this space :)

**Comment by kieranjol** [comment]
That's a really great idea - great project!
